### ISSUE TITLE
Playlist and Search Problems

### ISSUE THREAD

**Issue by saintchelo** [GPMDP/google-play-music-desktop-remote#12]
Hi
First of all I want to congratulate you on the outstanding GPMDP desktop app.
I am encountering some problems with the remote that I installed on my Galaxy S4 (android 4.4.2).
When I tap in some playlist my phone shows the songs in this playlist but if I tap in some music of this playlist, GPMDP does not start the song.
In the search, if for example I search for Madonna and go to the Artists tab (not all artist images are displayed - only a few are shown) and tap on the Madonna artist, the GPMDP desktop continues to show all Madonna refined searches and not Only Madonna.
At tab Artists in my phone, only some albums from the artist I've researched are shown, not all.
In short, the research part is very confusing.
Another thing I did not understand is the option tracks on my phone, when I tap, nothing is displayed.
GPMDP is working perfectly on my Windows 8.1.
Could it be that these problems with the remote would be related to the recent changes in Google Play Music website?
I would like to see the remote working fine, because it is an fantastic app.
Another question I have is that on this page https://www.googleplaymusicdesktopplayer.com/
Is saying that there is an equalizer, but I could not find any option.
Thank you very much for the attention and I hope that new versions of the remote come and that the problems are solved.
If you want, I can make a video showing these problems. Just ask me.
Regards
Marcelo

**Comment by MarshallOfSound** [comment]
For future reference an issue should be structured and have a clearly defined "issue" and scope.

I'll try to respond to each thing individually but these things look like they would be better served in chat rather than an issue.

> When I tap in some playlist my phone shows the songs in this playlist but if I tap in some music of this playlist, GPMDP does not start the song.

Give an example of a specific song and I can look into it

> In the search, if for example I search for Madonna and go to the Artists tab (not all artist images are displayed - only a few are shown) and tap on the Madonna artist, the GPMDP desktop continues to show all Madonna refined searches and not Only Madonna.

Currently selecting an Artist does nothing, this is by design

> At tab Artists in my phone, only some albums from the artist I've researched are shown, not all.

I'm not sure I understand what you mean?  We only show the search results that Google shows you, not everything.

> Is saying that there is an equalizer, but I could not find any option.

The equalizer has been disabled for a long time due to ongoing Audio API issues in Chromium.
